### ISSUE TITLE
Guides are cutoff when indented block has newline

### ISSUE THREAD

**Issue by azatoth** [preservim/vim-indent-guides#23]
When having indented code, but include blank lines between statements, which contains no spaces at all, the guide is cutoff.
I understand this could be assumed as logical as the indentation is pretty much removed, but generally you do not want to include lines containing only white space.

**Comment by mamiu** [comment]
@nathanaelkane: yes it's possible. A little bit hacky, but possible.

 Make a function that copies leading whitespace from the line before to the current line (if the current line is blank). But now you have the problem, if you save you'll have whitespace on empty lines. So call your function (e.g. toggleWhitespaceOnBlankLines ;-) ) before saving and after saving with this commands: `autocmd BufWritePre <buffer> call toggleWhitespaceOnBlankLines()` and `autocmd BufWritePost <buffer> call toggleWhitespaceOnBlankLines()`. Calling this function before leaving Vim would also make sense (because of the error message: "No write since last change..."). The related event is called `VimLeave`.

What do you think about that?

[Vim events: http://vimdoc.sourceforge.net/htmldoc/autocmd.html#autocmd-events]

**Comment by mharradon** [comment]
I would really love this feature if somebody thinks they can implement it.

**Comment by Tarmean** [comment]
The highlight on an empty line works if the cursor isn't on that line while creating it. Don't ask me why.
